### ISSUE TITLE
pod exporter settings use for thoses sample are ??

### ISSUE THREAD

**Issue by ghost** [powervr-graphics/WebGL_SDK#1]
Hello
what is the best setting in the exporter for webgl sdk to export my pod ?? 
i mean triangle list sorted ?? the documentation does not describe it...it a bit hard to guess

do you have idea ??
thank you 
Kind regards
david

**Comment by PVRDevTech** [comment]
Hi David,

Yes, sometimes it could be a bit difficult to guess the options from a hardwired demo. One easy way is to load the configuration from POD files included in the SDK. To do this right-click in the Configurations panel in PVRGeoPOD and point to an existing POD file. All the options will be set up as that file so you can export your model with the same configuration.

For our WebGL SDK we use. “Interleaved Vertex data” and “Indexed Triangle List”. Sorting is just an optimisation and it should not affect your example.

Regards.

Carlos.

**Comment by ghost** [comment]
Hello

i am using the 3ds max plug ing, the object is all back , the texture are not flip as well in the settings.
i tried both approach.
as well i have this issue  in pvranimation.js : 

if(this.data.matrices)
		{
			// TODO
			throw "TODO";
		}

it s really sad because POD model is the best around to hold animation and geometric structure.

david

**Comment by PVRDevTech** [comment]
Hi David,

Does your POD model display correctly on PVRShaman? If not, send the model to us and we should be able to have a look.
You do not need to export transformation matrices with your animation (it is less efficient). If you disable that option when exporting your model, the code in the SDK should work fine.

Regards.

Carlos.

**Comment by ghost** [comment]
Hello

the pod display very well on pvrshaman, i see the model without problem.
but when i just load it on webgl the prob start, i check inside the pod for visible part of the header to compare between what you have and what i have , but not much diff

thanks 
david
